# Generated by Django 4.0.6 on 2022-11-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('current_price', models.IntegerField()),
                ('minimum_price', models.IntegerField()),
                ('maximum_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('auto_stock_amount', models.IntegerField()),
                ('price_change_amount', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
        ),
    ]
