# Generated by Django 3.2.8 on 2022-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221117_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_quantity_change',
            field=models.IntegerField(default=100),
        ),
    ]
