# Generated by Django 3.2.8 on 2022-11-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_url',
        ),
    ]
